apiVersion: v1
kind: Service
metadata:
  name: prod-svc-todo
  namespace: apistone-prod
spec:
  selector:
    app: web
  ports:
   - protocol: TCP
     port: 8000
     targetPort: 3000
  type: LoadBalancer