apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-todo
  labels:
    app: web
  namespace: apistone-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers: 
      - image: 904089174636.dkr.ecr.us-east-1.amazonaws.com/fast-apistone-t2:prod-latest
        name: prod-todo
        imagePullPolicy: Always
 
        ports:
        - containerPort: 3000