apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-todo
  labels:
    app: web
  namespace: apistone-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers: 
      - image: 904089174636.dkr.ecr.us-east-1.amazonaws.com/fast-apistone-t2:stg-latest
        name: stg-todo
        imagePullPolicy: Always
 
        ports:
        - containerPort: 3000